# Site settings
title: Clean Blog
header-img: img/home-bg.jpg
email: ialjienye@gmail.com.com
copyright_name: startbootstrap-clean-blog-jekyll-gh-pages
description: "biodata ratna sari"
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://biodataratna.github.io"
twitter_username: SBootstrap
github_username:  sahrial
facebook_username:  sahrial
email_username:  syahrial.member@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
